version: '3'
services:
  pact_container_ubuntu:
    platform: linux/amd64
    image: hicsail/pact
    volumes:
      - ./Intel:/opt/app/Intel
      - ./Example:/opt/app/Example
      - ./Example_overlay_images:/opt/app/Example_overlay_images
      - ./Example_transient_data_files:/opt/app/Example_transient_data_files
    command: /opt/app/Intel/Intel_ID1_lcf.csv /opt/app/Intel/Intel.config /opt/app/Intel/modelParams_Intel.config --gridSteadyFile /opt/app/Intel/Intel.grid.steady
    container_name: pact_container_ubuntu
    
  visual_pact_container_ubuntu:
    image: hicsail/visualpact
    platform: linux/amd64
    volumes:
      - ./Intel:/opt/app/Intel
      - ./Example:/opt/app/Example
      - ./VisualPACT/Example_transient_data_files:/opt/app/VisualPACT/Example_transient_data_files
      - ./VisualPACT/Example_overlay_images:/opt/app/VisualPACT/Example_overlay_images
    # command: /opt/app/VisualPACT/Example_transient_data_files/IBMPower9transientheatsink_128x128.grid.cir.csv --overlay /opt/app/VisualPACT/Example_overlay_images/IBMPower9.png
    command: /opt/app/Intel/Intel.cir.csv --fps 20 --overlay /opt/app/VisualPACT/Example_overlay_images/Inteli7.PNG --dpi 100
    container_name: visual_pact_container_ubuntu
